### ISSUE TITLE
Comment in the README the primary difference between this and goldmark-meta

### ISSUE THREAD

**Issue by gwd** [abhinav/goldmark-frontmatter#36]
Searching for "markdown frontmatter" brought up this package first.  However, it looks like goldmark itself already has a ["metadata" extension](github.com/yuin/goldmark-meta) which can do something similar.  Skimming through the documentation, it I see two main differences:

1. Your extension can use TOML (with `+++` as delimiters) in addition to YAML
2. Your extension can marshal data into a struct, whereas goldmark-meta can only give you a `map[string]any`.

Anything else in particular why you decided to develop your own extension rather than using `goldmark-meta`?

Thanks!

**Comment by abhinav** [comment]
Thanks for opening this, @gwd.
Yeah, those are both the differences and the reason I developed the extension:
I wanted the option for a type-safe API instead of `map[string]any`.
I needed the ability to decode other popular frontmatter formats. ([Hugo](https://gohugo.io) supports TOML, so I wanted support.)
The extension can also be configured to recognize custom frontmatter formats.

One other difference: this extension does not provide the [WithTable](https://pkg.go.dev/github.com/yuin/goldmark-meta#WithTable) option to render the metadata as a table. YAML frontmatter can be arbitrarily complex structs, and those don't translate to a two-dimensional table well.

For context, I developed this extension to use in [stitchmd](https://github.com/abhinav/stitchmd). stitchmd transforms Markdown documents so it needed to support both popular frontmatter formats.

I've tried to list the features of this extension without referencing the goldmark-metadata extension, but maybe you're right and that isn't enough. I'll add some more to the README.
